#!/bin/sh

chmod 755 /etc/helium_gateway/install_update
chmod 755 /etc/init.d/helium_gateway
chmod 755 /usr/bin/helium_gateway

chmod 644 /etc/logrotate.d/helium_gateway
chmod 644 /usr/share/syslog-ng/include/tektelic/custom/helium-gateway.conf

/usr/sbin/update-rc.d helium_gateway defaults 90

# Update region config for Helium gateway
/etc/region-config.d/helium-region-configure

settings_file_to_update="/tmp/settings.toml.to-update"
old_settings_file="/etc/helium_gateway/settings.toml"
#Perform conversion Settings.toml only if it exists
if [ -e "${settings_file_to_update}" ] && [ -e "${old_settings_file}" ]; then
    echo "Converting the ${settings_file_to_update} file"

    cp "${old_settings_file}" "${old_settings_file}".backup

    # Replace listen_addr with listen
    sed -i 's/^listen_addr =/listen =/g' "${settings_file_to_update}"

    # update the keypair line
    sed -i 's/^keypair = \(.*\)/#keypair = \1/' "${settings_file_to_update}"

    sed -i '/^#keypair = /a ## ECC608 based\nkeypair = \"ecc:\/\/ttyO1:0&slot=0\"\n' "${settings_file_to_update}"

    # Replace update comment line
    sed -i 's/^# En\(able update checking\)/# Dis\1/' "${settings_file_to_update}"

    # Update enabled line
    sed -i 's/^enabled = true/enabled = false/' "${settings_file_to_update}"

    # Append max_packet line
    sed -i '/^store =/a max_packets = 20' "${settings_file_to_update}"

    # Replace public_key with pubkey
    sed -i 's/^public_key/pubkey/' "${settings_file_to_update}"

    cp "${settings_file_to_update}" "${old_settings_file}"

    rm "${settings_file_to_update}"

fi
# This package provides custom config for syslog. Reload config file to activate
if [ -x "/etc/init.d/syslog" ]; then
    "/etc/init.d/syslog" reload || true
fi

/etc/init.d/helium_gateway restart
