version: "3.7"

networks:
  helium:

services:
  gateway-rs:
    image: helium/gateway-rs
    build:
      context: .
    volumes:
      - './key.bin:/etc/helium_gateway/gateway_key.bin'
    #  - '/dev/i2c-1:/dev/i2c-1'
    #cap_add:
    #  - SYS_RAWIO
    environment:
      - GW_REGION=US915
      - GW_LOG_LEVEL=info 
      - GW_UPDATE_ENABLED=false
    #  - GW_KEYPAIR=ecc://i2c-1:96&slot=0
    networks:
      - helium
    expose:
      - 1680/udp
      - 4467/tcp
    ports:
      - 127.0.0.1:1680:1680/udp
      - 127.0.0.1:4467:4467/tcp
    restart: unless-stopped
