#!/bin/sh /etc/rc.common

START=99
STOP=99
USE_PROCD=1

PROG="/usr/bin/helium_gateway"
CONFIGURATION_FILE="/etc/helium_gateway/settings.toml"

start_service() {
    include /lib/functions

    procd_open_instance
    
    procd_set_param command $PROG -c $CONFIGURATION_FILE server
    procd_set_param file $CONFIGURATION_FILE
    procd_set_param stdout 1 
    procd_set_param stderr 1 
    procd_set_param respawn

    procd_close_instance
}
