#!/bin/sh /etc/rc.common

START=99
STOP=99
USE_PROCD=1

PROG="/usr/bin/helium_gateway"
CONFIG_DIR="/etc/helium_gateway"

start_service() {
    include /lib/functions

    procd_open_instance

    procd_set_param command $PROG -c $CONFIG_DIR server
    procd_set_param file $CONFIG_DIR
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn

    procd_close_instance
}
