[package]
name = "entropy"
version = "0.1.0"
authors = ["Marc Nijdam <marc@nova-labs.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
serde = {version = "1", features = ["derive"]}
base64 = "0"

[dev-dependencies]
serde_json = "1"