#!/bin/sh

### BEGIN INIT INFO
# Provides: helium_gateway
# Required-Start: $network $local_fs
# Required-Stop: $network $local_fs
# Should-Start: $syslog $named
# Should-Stop: $syslog $named
# Short-Description: start and stop helium_gateway
# Description: Helium Gateway
### END INIT INFO

NAME="helium_gateway"
ENABLED="yes"

PID_FILE=/var/run/helium_gateway.pid
CONFIGURATION_FILE="/etc/helium_gateway/settings.toml"
BINARY=/usr/bin/helium_gateway
OPTS="--daemon -c $CONFIGURATION_FILE server"

[ -f /etc/default/$NAME ] && source /etc/default/$NAME

case "$1" in
  start)
	echo -n "Starting $NAME: "
	start-stop-daemon --start -x "$BINARY" -- $OPTS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $NAME: "
	start-stop-daemon --stop -x "$BINARY"
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $NAME: "
	start-stop-daemon --stop -x "$BINARY"
	sleep 1
	start-stop-daemon --start -x "$BINARY" -- $OPTS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0