#!/bin/sh -e

# move into place
mv "${1}" /user/.updates
# sync to make sure it moved across partitions
sync
# mark ready for update
kerosd -u
# stop service to avoid restart
/etc/init.d/helium_gateway stop
reboot
