[package]
name = "${CARGO_MAKE_CRATE_NAME}"
description = "${CARGO_MAKE_CRATE_DESCRIPTION}"
version = "${CARGO_MAKE_CRATE_VERSION}"
authors = ["Marc Nijdam <marc@helium.com>"]
edition = "2018"
license = "${CARGO_MAKE_CRATE_LICENSE}"

[workspace]

[[bin]]
name = "helium_gateway"
path = "data/usr/bin/helium_gateway"

[package.metadata.deb]
name = "helium_gateway"
license-file = ["${CARGO_MAKE_WORKING_DIRECTORY}/LICENSE", "0"]
extended-description = """\
The Helium Gateway to attach your LoRa gateway to the Helium Blockchain.
"""
depends = "curl"
section = "utility"
priority = "optional"
maintainer-scripts = "control/"
conf-files = ["/etc/helium_gateway/settings.toml"]
assets = [
    # binary
    ["data/usr/bin/helium_gateway", "/usr/bin/helium_gateway", "755"],
    # assets
    ["data/etc/helium_gateway/*", "/etc/helium_gateway", "644"]
]

[package.metadata.deb.systemd-units]
enable = true
unit-name = "helium_gateway"
