on:
  push:
    tags: ['v*']

name: release

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - klkgw
          - ramips_24kec
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v2

      - name: install cross
        uses: jaxxstorm/action-install-gh-release@release/v1-alpha
        env:
          ## Allow cross install into PATH
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with: 
          repo: rust-embedded/cross

      - name: build ipk
        run: cargo make --profile ${{ matrix.target }} ipk

      - name: name asset
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: create release
        uses: softprops/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: Release ${{ steps.vars.outputs.tag }}
          files: target/ipk/helium-gateway-${{ steps.vars.output.tag }}-${{ matrix.target }}.ipk 
